#!/bin/bash

verilator --trace \
   --cc rtl/x_top.sv \
   --cc ../x_top_rv32i/rtl/x_top_rv32i.sv \
   --cc ../x_top_mem/rtl/x_top_mem.sv \
   --cc ../x_top_uart_tx/rtl/x_top_uart_tx.sv \
   --cc ../x_top_uart_rx/rtl/x_top_uart_rx.sv 

