#!/bin/bash
echo "========================================================"
echo "Running synth..."
rm -f syn.log
yosys -p 'synth_ice40 -top x_top -blif x_top.blif -json x_top.json' rtl/x_top.sv ../x_top_rv32i/rtl/x_top_rv32i.sv ../x_top_mem/rtl/x_top_mem.sv ../x_top_uart_tx/rtl/x_top_uart_tx.sv ../x_top_uart_rx/rtl/x_top_uart_rx.sv > syn.log
cat syn.log | grep -A30 statistics
echo "========================================================"
echo "Running place and route..."
rm -f pnr.log
nextpnr-ice40 --hx8k --json x_top.json --package ct256 --pcf etc/x_top.pcf --asc x_top.asc &> pnr.log
cat pnr.log | grep -A6 "Device utilisation"
echo "========================================================"
echo "Running Timing check..."
icetime -d hx8k x_top.asc > x_top.time
cat x_top.time
