#!/bin/bash
echo "========================================================"
echo "Running synth..."
rm -f syn.log
yosys -p 'synth_ice40 -top x_top_uart_test -blif x_top_uart_test.blif -json x_top_uart_test.json' rtl/x_top_uart_test.sv ../x_top_uart_tx/rtl/x_top_uart_tx.sv ../x_top_uart_rx/rtl/x_top_uart_rx.sv > syn.log
cat syn.log | grep -A30 statistics
echo "========================================================"
echo "Running place and route..."
rm -f pnr.log
nextpnr-ice40 --hx8k --json x_top_uart_test.json --package ct256 --pcf etc/x_top_uart_test.pcf --asc x_top_uart_test.asc &> pnr.log
cat pnr.log | grep -A6 "Device utilisation"
echo "========================================================"
echo "Running Timing check..."
icetime -d hx8k x_top_uart_test.asc > x_top_uart_test.time
cat x_top_uart_test.time
